---
format: odt
reference-doc: feasibilityreference.odt
editor: visual
---

3.sectionNumber.1 The River Condition Assessment was completed according to the Modular River Physical (MoRPh) Survey methodology as outlined by within the MoRPh Manual 2022 (Gurnell et al. 2022).

3.sectionNumber.2 The surveys were completed by trained and accredited personnel.

### MoRPh Surveys

3.sectionNumber.3 The River Condition Assessment consists of a series of visual inspections of sections, or sub-reaches, of a river recording the extent, and frequency of a large number of physical characteristics, such as height, width and shape, and material of the bank and bed, as well as other physical features such as presence and extent of bars and islands. The nature of the water flow is also considered, recording the nature of the water surface such as whether it is smooth, rippled, or unbroken waves. Vegetation within the river and along the bank and bank top is also recorded.

### Desk Study

3.sectionNumber.4 The methodology includes a desk study that identifies the wider length of the river that is relatively uniform, or reach of the river, that the site falls within, which is often several kilometres long. The study measures several characteristics such as the length, sinuosity, and gradient, which along with the information collected during the MoRPh surveys are used to categorise the river as one of 13 river types found in the UK.

3.sectionNumber.5 The results of the surveys and desk top study are used to calculate a condition score which is typically between 0 and 2, though exceptionally poor or good quality rivers can score above or below this, respectively. This score is then used to allocate a condition to the river, based on the determined river type, with the sub-reach of the river categorised as either Poor, Fairly Poor, Moderate, Fairly Good, or Good.

3.sectionNumber.6 Finally, the river is assessed as to whether it is over deep, i.e disconnected from the floodplain. Many streams and rivers within England, have a long history of channel modifications, as a result of which they have become ‘over deep’, and are to some extent hydrologically and ecologically disconnected from their riparian margins and floodplains. Over deep channels may support a diverse range of physical habitats but if these are hydrologically disconnected to some degree it reduces their potential to support biodiversity.

3.sectionNumber.7 Where river sub-reaches are considered to be over deep, the resultant condition is downgraded by one category e.g., Fairly Good to Moderate.
